services:
  usuario-ms:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ms-usuario
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-usuario:5432/vida_db
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - MI_API_KEY=${USUARIO_API_KEY}
    depends_on:
      db-usuario:
        condition: service_healthy 
  db-usuario:
    image: postgres:15-alpine
    container_name: postgres-usuario
    environment:
      - POSTGRES_DB=vida_db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d vida_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data_usuario:/var/lib/postgresql/data

volumes:
  pg_data_usuario: